CONFIG_LOG=y
CONFIG_THREAD_NAME=y
# Specifies the maximum amount of time (in ms) a thread can execute 
# before other threads of equal priority are given an opportunity to run.
CONFIG_TIMESLICE_SIZE=1
